### PR TITLE
Remove date from pages

### PR DESCRIPTION
**Pull request by turtle96**
#### Remove date from title header

image

### CODE REVIEW

**Comment by jia1** [comment]
I don't think I can merge this because this means the blog post will lose its date too. Example: https://nuscomputing.com/post/ay17181-egm-1/

**Review by jia1 — COMMENTED** [review]
Nope.

**Comment by turtle96** [comment]
@jia1 no worries, it's possible to make alternate layout for main pages, and post pages. Might need more changes though (i.e. file structure?)
Currently post pages also looks a little strange, aligned more to left, not center (because of sidemenu div iirc)
image

Are you okay with it? Or you wanna leave it as same layout for main and post pages?

**Comment by jia1** [comment]
@turtle96 

I guess the left-alignment is acceptable for now. For long posts, the author may opt to add in sections.

**Pull request closed without merging**
